sudo: false

os:
  - linux

language:
  - c

services:
  - docker

git:
  depth: false

before_install:
  - docker pull debian:testing

script:
  - docker build -t buildenv .
  - docker run buildenv /bin/sh -c "cd root/tlwbe && mk-build-deps -i -t\"apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y\" && git checkout -b tmp && gbp buildpackage --git-ignore-new --no-sign && dpkg -i /root/tlwbe_*.deb"
#  - docker run withgit /bin/sh -c "cd /root && TRAVIS=true CC=$CC CXX=$CXX meson builddir && ninja -C builddir"
