#pragma once

#ifndef TLWBE_DEBUG_MOSQUITTO
#define TLWBE_DEBUG_MOSQUITTO		0
#endif

#ifndef TLWBE_DEBUG_PRINTPACKETS
#define	TLWBE_DEBUG_PRINTPACKETS	0
#endif

#ifndef TLWBE_DEBUG_REPACKPACKETS
#define TLWBE_DEBUG_REPACKPACKETS	1
#endif

