FROM debian:testing
RUN apt-get -qq update
RUN apt-get -qq dist-upgrade
RUN apt-get -qq install -y mosquitto \
                           python3-pip \
                           python3-pytest \
                           python3-pytest-asyncio \
                           python3-paho-mqtt \
                           cython3 \
                           git
ADD . /root/tlwbe
